name: Action Logger

on:
  workflow_dispatch:
    inputs:
      cve:
        type: string
      run_id:
        type: string
      repo:
        type: string
      snyk_target:
        type: string
      pager_service:
        type: string
     
jobs:
  zero_day_check:
    runs-on: ubuntu-latest
    steps:
    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ inputs.run_id }}
        logMessage: |
           Starting action 😎
           
    # - name: Deploy image to environment
    # To-Do: Snyk scan
    - name: Zero day check
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://docs.getport.io/
        runId: ${{ inputs.run_id }}
        logMessage: |
          Checking for CVE ${{ inputs.cve }} with Snyk
        echo: "Snyk target: ${{ inputs.snyk_target }}"
        echo: "Repo: ${{ inputs.repo }}"

    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://docs.getport.io/
        runId: ${{ inputs.run_id }}
        logMessage: |
          Action completed successfully! ✅
