name: Flix Zeroday Scanner

on:
  workflow_dispatch:
    inputs:
      cve:
        type: string
      run_id:
        type: string
      repo:
        type: string
      snyk_target:
        type: string
      pager_service:
        type: string
     
jobs:
  zero_day_check:
    runs-on: ubuntu-latest
    steps:
    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ inputs.run_id }}
        logMessage: |
           Starting action 😎
           
    # - name: Deploy image to environment
    # To-Do: Snyk scan
    - name: Zero day check
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://docs.getport.io/
        runId: ${{ inputs.run_id }}
        logMessage: |
          Checking for CVE ${{ inputs.cve }} with Snyk
    - name: Snyk Target and Repo
      run: |
        echo "Repo: ${{ inputs.repo }}, Snyk Target: ${{ inputs.snyk_target }}"

    - name: Clone target repo
      run: git clone https://github.com/${{ inputs.repo }}.git
    
    - name: ${{ inputs.cve }} check
      run: |
        echo "This where I get to do a snyk scan with snyk test --json"

    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://docs.getport.io/
        runId: ${{ inputs.run_id }}
        logMessage: |
          Action completed successfully! ✅
